@startuml
left to right direction
actor Vendég as G
package Aquapark {
    actor Dolgozó as W
    usecase (Összes használatban lévő óra lekérdezése) as WIU
    usecase (Adott vendég csúszda használatának lekérdezése) as GSU
    usecase (Napi vagy havi statisztika elkészítése a csúszdákról) as S
    usecase (Saját statisztika lekérdezése) as OwnStat
    usecase (Jelenlegi költségek lekérdezése) as CurrCosts

    G --> OwnStat
    G --> CurrCosts
    package Recepció {
        usecase (Beléptetés) as CI
        usecase (Kijelentkeztetés) as CO
        usecase (Vendég számára számla előállítása) as Invoice
        CO .> Invoice : include
    }
    CI <-- W
    G -> CI
    CO <-- W
    G -> CO
    WIU <-- W
    GSU <-- W
    S <-- W
    Invoice <-- W
}
@enduml